module.exports = Object.freeze({
    HTTP_OK: 200,
    HTTP_CREATED: 201,
    HTTP_BAD_REQUEST: 400,
    HTTP_UNAUTHORIZED: 401,
    HTTP_INTERNAL_SERVER_ERROR: 500,
    ADMIN_ROLE_ID: 'ADMIN_ROLE',
    USER_ROLE_ID: 'USER_ROLE'

});